import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/main-nav";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Next 15 RC Practice",
  description: "Next 15 generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} flex flex-col min-h-dvh`}
      >
        <div className="bg-blue-500 h-17">
          <div className="max-w-screen-2xl m-auto">
            <Navbar />
          </div>
        </div>
        <div className="flex-1 max-w-screen-2xl min-h-full overflow-y-auto">
          {children}
        </div>
      </body>
    </html>
  );
}
